# Generated by Django 2.2.4 on 2019-12-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mobile_no', models.IntegerField()),
                ('customer_age', models.FloatField()),
                ('customer_city', models.CharField(max_length=30)),
            ],
        ),
    ]
